export const POST_BUSINESS = 'POST_BUSINESS';
export const POST_BUSINESS_SUCCESS = 'POST_BUSINESS_SUCCESS';
export const POST_BUSINESS_ERROR = 'POST_BUSINESS_ERROR';

export const PUT_BUSINESS = 'PUT_BUSINESS';
export const PUT_BUSINESS_SUCCESS = 'PUT_BUSINESS_SUCCESS';
export const PUT_BUSINESS_ERROR = 'PUT_BUSINESS_ERROR';

export const GET_BUSINESS = 'GET_BUSINESS';
export const GET_BUSINESS_SUCCESS = 'GET_BUSINESS_SUCCESS';
export const GET_BUSINESS_ERROR = 'GET_BUSINESS_ERROR';

