export const POST_CONFIGURABLE_CATEGORY = 'POST_CONFIGURABLE_CATEGORY';
export const POST_CONFIGURABLE_CATEGORY_SUCCESS = 'POST_CONFIGURABLE_CATEGORY_SUCCESS';
export const POST_CONFIGURABLE_CATEGORY_ERROR = 'POST_CONFIGURABLE_CATEGORY_ERROR';

export const PUT_CONFIGURABLE_CATEGORY = 'PUT_CONFIGURABLE_CATEGORY';
export const PUT_CONFIGURABLE_CATEGORY_SUCCESS = 'PUT_CONFIGURABLE_CATEGORY_SUCCESS';
export const PUT_CONFIGURABLE_CATEGORY_ERROR = 'PUT_CONFIGURABLE_CATEGORY_ERROR';

export const GET_CONFIGURABLE_CATEGORY = 'GET_CONFIGURABLE_CATEGORY';
export const GET_CONFIGURABLE_CATEGORY_SUCCESS = 'GET_CONFIGURABLE_CATEGORY_SUCCESS';
export const GET_CONFIGURABLE_CATEGORY_ERROR = 'GET_CONFIGURABLE_CATEGORY_ERROR';

export const POST_CONFIGURABLE_ITEM = 'POST_CONFIGURABLE_ITEM';
export const POST_CONFIGURABLE_ITEM_SUCCESS = 'POST_CONFIGURABLE_ITEM_SUCCESS';
export const POST_CONFIGURABLE_ITEM_ERROR = 'POST_CONFIGURABLE_ITEM_ERROR';

export const PUT_CONFIGURABLE_ITEM = 'PUT_CONFIGURABLE_ITEM';
export const PUT_CONFIGURABLE_ITEM_SUCCESS = 'PUT_CONFIGURABLE_ITEM_SUCCESS';
export const PUT_CONFIGURABLE_ITEM_ERROR = 'PUT_CONFIGURABLE_ITEM_ERROR';

export const GET_CONFIGURABLE_ITEM = 'GET_CONFIGURABLE_ITEM';
export const GET_CONFIGURABLE_ITEM_SUCCESS = 'GET_CONFIGURABLE_ITEM_SUCCESS';
export const GET_CONFIGURABLE_ITEM_ERROR = 'GET_CONFIGURABLE_ITEM_ERROR';

