
export const POST_CONFIG = 'POST_CONFIG';
export const POST_CONFIG_SUCCESS = 'POST_CONFIG_SUCCESS';
export const POST_CONFIG_ERROR = 'POST_CONFIG_ERROR';

export const PUT_CONFIG = 'PUT_CONFIG';
export const PUT_CONFIG_SUCCESS = 'PUT_CONFIG_SUCCESS';
export const PUT_CONFIG_ERROR = 'PUT_CONFIG_ERROR';

export const GET_CONFIG = 'GET_CONFIG';
export const GET_CONFIG_SUCCESS = 'GET_CONFIG_SUCCESS';
export const GET_CONFIG_ERROR = 'GET_CONFIG_ERROR';

export const GET_CONFIGS = 'POST_CONFIGS';
export const GET_CONFIGS_SUCCESS = 'POST_CONFIGS_SUCCESS';
export const GET_CONFIGS_ERROR = 'POST_CONFIGS_ERROR';
