export const POST_LOCATION = 'POST_LOCATION';
export const POST_LOCATION_SUCCESS = 'POST_LOCATION_SUCCESS';
export const POST_LOCATION_ERROR = 'POST_LOCATION_ERROR';

export const PUT_LOCATION = 'PUT_LOCATION';
export const PUT_LOCATION_SUCCESS = 'PUT_LOCATION_SUCCESS';
export const PUT_LOCATION_ERROR = 'PUT_LOCATION_ERROR';

export const GET_LOCATION = 'GET_LOCATION';
export const GET_LOCATION_SUCCESS = 'GET_LOCATION_SUCCESS';
export const GET_LOCATION_ERROR = 'GET_LOCATION_ERROR';

