export const POST_MENU_CATEGORY = 'POST_MENU_CATEGORY';
export const POST_MENU_CATEGORY_SUCCESS = 'POST_MENU_CATEGORY_SUCCESS';
export const POST_MENU_CATEGORY_ERROR = 'POST_MENU_CATEGORY_ERROR';

export const PUT_MENU_CATEGORY = 'PUT_MENU_CATEGORY';
export const PUT_MENU_CATEGORY_SUCCESS = 'PUT_MENU_CATEGORY_SUCCESS';
export const PUT_MENU_CATEGORY_ERROR = 'PUT_MENU_CATEGORY_ERROR';

export const GET_MENU_CATEGORY = 'GET_MENU_CATEGORY';
export const GET_MENU_CATEGORY_SUCCESS = 'GET_MENU_CATEGORY_SUCCESS';
export const GET_MENU_CATEGORY_ERROR = 'GET_MENU_CATEGORY_ERROR';

export const POST_MENU_ITEM = 'POST_MENU_ITEM';
export const POST_MENU_ITEM_SUCCESS = 'POST_MENU_ITEM_SUCCESS';
export const POST_MENU_ITEM_ERROR = 'POST_MENU_ITEM_ERROR';

export const PUT_MENU_ITEM = 'PUT_MENU_ITEM';
export const PUT_MENU_ITEM_SUCCESS = 'PUT_MENU_ITEM_SUCCESS';
export const PUT_MENU_ITEM_ERROR = 'PUT_MENU_ITEM_ERROR';

export const GET_MENU_ITEM = 'GET_MENU_ITEM';
export const GET_MENU_ITEM_SUCCESS = 'GET_MENU_ITEM_SUCCESS';
export const GET_MENU_ITEM_ERROR = 'GET_MENU_ITEM_ERROR';

