export const POST_PRODUCT_CATEGORY = 'POST_PRODUCT_CATEGORY';
export const POST_PRODUCT_CATEGORY_SUCCESS = 'POST_PRODUCT_CATEGORY_SUCCESS';
export const POST_PRODUCT_CATEGORY_ERROR = 'POST_PRODUCT_CATEGORY_ERROR';

export const PUT_PRODUCT_CATEGORY = 'PUT_PRODUCT_CATEGORY';
export const PUT_PRODUCT_CATEGORY_SUCCESS = 'PUT_PRODUCT_CATEGORY_SUCCESS';
export const PUT_PRODUCT_CATEGORY_ERROR = 'PUT_PRODUCT_CATEGORY_ERROR';

export const GET_PRODUCT_CATEGORY = 'GET_PRODUCT_CATEGORY';
export const GET_PRODUCT_CATEGORY_SUCCESS = 'GET_PRODUCT_CATEGORY_SUCCESS';
export const GET_PRODUCT_CATEGORY_ERROR = 'GET_PRODUCT_CATEGORY_ERROR';

export const POST_PRODUCT_ITEM = 'POST_PRODUCT_ITEM';
export const POST_PRODUCT_ITEM_SUCCESS = 'POST_PRODUCT_ITEM_SUCCESS';
export const POST_PRODUCT_ITEM_ERROR = 'POST_PRODUCT_ITEM_ERROR';

export const PUT_PRODUCT_ITEM = 'PUT_PRODUCT_ITEM';
export const PUT_PRODUCT_ITEM_SUCCESS = 'PUT_PRODUCT_ITEM_SUCCESS';
export const PUT_PRODUCT_ITEM_ERROR = 'PUT_PRODUCT_ITEM_ERROR';

export const GET_PRODUCT_ITEM = 'GET_PRODUCT_ITEM';
export const GET_PRODUCT_ITEM_SUCCESS = 'GET_PRODUCT_ITEM_SUCCESS';
export const GET_PRODUCT_ITEM_ERROR = 'GET_PRODUCT_ITEM_ERROR';

