export const GET_DAY_REPORT = 'GET_DAY_REPORT';
export const GET_DAY_REPORT_SUCCESS ='GET_DAY_REPORT_SUCCESS';
export const GET_DAY_REPORT_ERROR = 'GET_DAY_REPORT_ERROR';

export const GET_MONTH_REPORT = 'GET_MONTH_REPORT';
export const GET_MONTH_REPORT_SUCCESS = 'GET_MONTH_REPORT_ERROR';
export const GET_MONTH_REPORT_ERROR = 'GET_MONTH_REPORT_ERROR';

export const SET_REPORT_DATE = 'SET_REPORT_DATE';
export const SET_REPORT_MONTH = 'SET_REPORT_MONTH';