export const POST_SERVICE = 'POST_SERVICE';
export const POST_SERVICE_SUCCESS = 'POST_SERVICE_SUCCESS';
export const POST_SERVICE_ERROR = 'POST_SERVICE_ERROR';

export const PUT_SERVICE = 'PUT_SERVICE';
export const PUT_SERVICE_SUCCESS = 'PUT_SERVICE_SUCCESS';
export const PUT_SERVICE_ERROR = 'PUT_SERVICE_ERROR';

export const GET_SERVICE = 'GET_SERVICE';
export const GET_SERVICE_SUCCESS = 'GET_SERVICE_SUCCESS';
export const GET_SERVICE_ERROR = 'GET_SERVICE_ERROR';

