export const GET_APPOINTMENT_BYDATE = 'GET_APPOINTMENT_BYDATE';
export const GET_APPOINTMENT_BYDATE_SUCCESS = 'GET_APPOINTMENT_BYDATE_SUCCESS';
export const GET_APPOINTMENT_BYDATE_ERROR = 'GET_APPOINTMENT_BYDATE_ERROR';

export const SET_APPOINTMENT_BYROOM = 'SET_APPOINTMENT_BYROOM';
export const SET_APPOINTMENT_BYPRACT = 'SET_APPOITMENT_BYPRACT'

export const SET_APPOINTMENT_DATE = 'SET_APPOINTMENT_DATE';
export const SET_APPOINTMENT_DATETIME = 'SET_APPOINTMENT_DATETIME';

export const POST_APPOINTMENT = 'POST_APPOINTMENT';
export const PUT_APPOINTMENT = 'PUT_APPOINTMENT';
export const DELETE_APPOINTMENT = 'DELETE_APPOINTMENT';
export const BUILD_INVOICE = 'BUILD_INVOICE';

export const GET_PRACTITIONERS = 'GET_PRACTITIONERS';
export const GET_PRACTITIONERS_SUCCESS = 'GET_PRACTITIONERS_SUCCESS'
export const GET_PRACTITIONERS_ERROR = 'GET_PRACTITIONERS_ERROR'
export const GET_CLIENTS = 'GET_CLIENTS';
export const GET_CLIENTS_SUCCESS = 'GET_CLIENTS_SUCCESS';
export const GET_CLIENTS_ERROR = 'GET_CLIENTS_ERROR';
export const GET_SERVICES = 'GET_SERVICES';
export const GET_SERVICES_SUCCESS = 'GET_SERVICES_SUCCESS';
export const GET_SERVICES_ERROR = 'GET_SERVICES_ERROR';