
export const SET_CLIENT_LOADING = 'SET_CLIENT_LOADING';
export const SET_CLIENT_SEARCHKEY = 'SET_CLIENT_SEARCHKEY';

export const SEARCH_CLIENT_MEMBER = 'SEARCH_CLIENT_MEMBER';
export const SEARCH_CLIENT_MEMBER_SUCCESS = 'SEARCH_CLIENT_MEMBER_SUCCESS';
export const SEARCH_CLIENT_MEMBER_ERROR = 'SEARCH_CLIENT_MEMBER_ERROR';

export const SEARCH_CLIENT_FAMILY = 'SEARCH_CLIENT_FAMILY';
export const SEARCH_CLIENT_FAMILY_SUCCESS = 'SEARCH_CLIENT_FAMILY_SUCCESS';
export const SEARCH_CLIENT_FAMILY_ERROR = 'SEARCH_CLIENT_FAMILY_ERROR';

export const POST_CLIENT_FAMILY = 'POST_CLIENT_FAMILY';
export const POST_CLIENT_FAMILY_SUCCESS = 'POST_CLIENT_FAMILY_SUCCESS'
export const POST_CLIENT_FAMILY_ERROR = 'POST_CLIENT_FAMILY_ERROR'

export const PUT_CLIENT_FAMILY = 'PUT_CLIENT_FAMILY';
export const PUT_CLIENT_FAMILY_SUCCESS = 'PUT_CLIENT_FAMILY_SUCCESS';
export const PUT_CLIENT_FAMILY_ERROR = 'PUT_CLIENT_FAMILY_ERROR';
